spring:
  application:
    name: rsfn-connect

rsfn:
  credentials:
    # Define qual provedor de credenciais será usado: "hsm" ou "kms"
    provider-name: "hsm"

    hsm:
      # O conteúdo do arquivo de configuração do provider PKCS#11
      # Exemplo: name = HSMAdapter\nlibrary = /opt/hsm/lib/libpkcs11.so\nslot = 0
      pkcs11-config: "name = MyHSM\nlibrary = /usr/lib/libckteec.so"
      password: ${HSM_PIN} # Use Vault ou Secrets Manager para isso!
      alias: "meu-certificado-rsfn"

    kms:
      key-id: "alias/my-kms-key"
      certificate-arn: "arn:aws:acm:us-east-1:123456789012:certificate/your-cert-id"